// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6XJJIzDpgLLhBFUQp_J6q2ZadYfqMd2M',
    appId: '1:815269820749:web:14b7228965ee053ca09f04',
    messagingSenderId: '815269820749',
    projectId: 'bloc-efc3a',
    authDomain: 'bloc-efc3a.firebaseapp.com',
    storageBucket: 'bloc-efc3a.firebasestorage.app',
    measurementId: 'G-WHL0YN1VY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTJ76gtxXvMeGFS1G6b_qWgusjUyHGX9A',
    appId: '1:815269820749:android:2f0cf92577a38081a09f04',
    messagingSenderId: '815269820749',
    projectId: 'bloc-efc3a',
    storageBucket: 'bloc-efc3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAib2bwzJw9hcc6FA5f_3spcWA3E1F6AAw',
    appId: '1:815269820749:ios:a3f63d0ee58b5f45a09f04',
    messagingSenderId: '815269820749',
    projectId: 'bloc-efc3a',
    storageBucket: 'bloc-efc3a.firebasestorage.app',
    iosBundleId: 'com.example.proyectomovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAib2bwzJw9hcc6FA5f_3spcWA3E1F6AAw',
    appId: '1:815269820749:ios:a3f63d0ee58b5f45a09f04',
    messagingSenderId: '815269820749',
    projectId: 'bloc-efc3a',
    storageBucket: 'bloc-efc3a.firebasestorage.app',
    iosBundleId: 'com.example.proyectomovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6XJJIzDpgLLhBFUQp_J6q2ZadYfqMd2M',
    appId: '1:815269820749:web:ea0c103f422c43c1a09f04',
    messagingSenderId: '815269820749',
    projectId: 'bloc-efc3a',
    authDomain: 'bloc-efc3a.firebaseapp.com',
    storageBucket: 'bloc-efc3a.firebasestorage.app',
    measurementId: 'G-GV4MZDJCTC',
  );

}